# Generated by Django 3.0.6 on 2020-05-10 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200510_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
