# Generated by Django 3.0.6 on 2020-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pages_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
